#!/usr/bin/env bash
#
cut -d: -f -7 /etc/passwd | while IFS=":" read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND_OR_SHELL
do
echo "The user ${USERNAME} is part of the ${GROUP_ID} gang, lives in ${HOME_DIRECTORY} and rides ${COMMAND_OR_SHELL}. ${USER_ID}'s place is protected by the passcode ${PASSWORD}, more info about the user here: ${USER_ID_INFO}"
done
