#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
i=1
echo "Hour: 0"
while [ $i -le 13 ]
do
	j=1
	while [ $j -lt 60 ]
	do
		echo "$j"
	((j++))
	done

	if ((i <= 12))
	then
		echo "Hour: $i"
	fi
((i++))
done
